/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StayRouteImport } from './routes/stay'
import { Route as SearchRouteImport } from './routes/search'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FoodRouteImport } from './routes/food'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SuccessRouteImport } from './routes/Success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiWebsearchRouteImport } from './routes/api/websearch'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/Success',
  path: '/Success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/hotels/$slug',
  path: '/hotels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiWebsearchRoute = ApiWebsearchRouteImport.update({
  id: '/api/websearch',
  path: '/api/websearch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Success': typeof SuccessRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/food': typeof FoodRoute
  '/join': typeof JoinRoute
  '/search': typeof SearchRoute
  '/stay': typeof StayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/websearch': typeof ApiWebsearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Success': typeof SuccessRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/food': typeof FoodRoute
  '/join': typeof JoinRoute
  '/search': typeof SearchRoute
  '/stay': typeof StayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/websearch': typeof ApiWebsearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Success': typeof SuccessRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/food': typeof FoodRoute
  '/join': typeof JoinRoute
  '/search': typeof SearchRoute
  '/stay': typeof StayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/websearch': typeof ApiWebsearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Success'
    | '/about'
    | '/ai'
    | '/blog'
    | '/business'
    | '/contact'
    | '/explore'
    | '/food'
    | '/join'
    | '/search'
    | '/stay'
    | '/api/chat'
    | '/api/websearch'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/places/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Success'
    | '/about'
    | '/ai'
    | '/blog'
    | '/business'
    | '/contact'
    | '/explore'
    | '/food'
    | '/join'
    | '/search'
    | '/stay'
    | '/api/chat'
    | '/api/websearch'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/places/$slug'
  id:
    | '__root__'
    | '/'
    | '/Success'
    | '/about'
    | '/ai'
    | '/blog'
    | '/business'
    | '/contact'
    | '/explore'
    | '/food'
    | '/join'
    | '/search'
    | '/stay'
    | '/api/chat'
    | '/api/websearch'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/places/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuccessRoute: typeof SuccessRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  FoodRoute: typeof FoodRoute
  JoinRoute: typeof JoinRoute
  SearchRoute: typeof SearchRoute
  StayRoute: typeof StayRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiWebsearchRoute: typeof ApiWebsearchRoute
  HotelsSlugRoute: typeof HotelsSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Success': {
      id: '/Success'
      path: '/Success'
      fullPath: '/Success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/hotels/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/websearch': {
      id: '/api/websearch'
      path: '/api/websearch'
      fullPath: '/api/websearch'
      preLoaderRoute: typeof ApiWebsearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuccessRoute: SuccessRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  FoodRoute: FoodRoute,
  JoinRoute: JoinRoute,
  SearchRoute: SearchRoute,
  StayRoute: StayRoute,
  ApiChatRoute: ApiChatRoute,
  ApiWebsearchRoute: ApiWebsearchRoute,
  HotelsSlugRoute: HotelsSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
